<script src="<?php echo e(asset('dependencies/popper.js/popper.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/jquery/jquery.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/bootstrap/js/bootstrap.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/jquery.appear/jquery.appear.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/jquery.parallax-scroll/jquery.parallax-scroll.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/gmap3/js/gmap3.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/owl.carousel/js/owl.carousel.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/slick/js/slick.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/counter-up/jquery.counterup.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/waypoints/jquery.waypoints.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/select2/js/select2.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/isotope-layout/isotope.pkgd.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/imagesloaded/imagesloaded.pkgd.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/meanmenu/js/jquery.meanmenu.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/Parallaxie-master/parallaxie.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/nivo-slider/js/jquery.nivo.slider.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/nivo-slider/js/home.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/wow/js/wow.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/knob/jquery.knob.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/countdown/jquery.countdown.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/page-piling/js/jquery.pagepiling.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/tilt/tilt.jquery.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/theia-sticky-sidebar/theia-sticky-sidebar.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/theia-sticky-sidebar/resize-sensor.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/magnific-popup/js/jquery.magnific-popup.min.js')); ?>"></script>
<script src="<?php echo e(asset('dependencies/validator/validator.min.js')); ?>"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB13ZAvCezMx5TETYIiGlzVIq65Mc2FG5g"></script>
<?php /**PATH C:\xampp\htdocs\accredination.co.uk\resources\views/includes/dependencies.blade.php ENDPATH**/ ?>